version: 2.1
orbs:
  heroku: circleci/heroku@1.2.3
workflows:
  heroku_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - heroku/deploy-via-git:
          requires:
            - build
          filter:
            branch:
              only: master