version: 2.1
orbs:
  heroku: circleci/heroku@1.2.3
workflows:
  heroku_deploy:
    jobs:
      - node/test:
          version: 10.19.0
          filter:
            branches:
              only: master
      - build:
          requires: 
            - node/test
          filter:
            branches:
              only: master
      - heroku/deploy-via-git:
          requires:
            - build
          filter:
            branch:
              only: master