jobs:
  deploy:
    executor: heroku/default
    filters:
      branches:
        only: master
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
orbs:
  heroku: circleci/heroku@1.2.3
version: 2.1
workflows:
  heroku_deploy:
    jobs:
      - deploy