version: 2.1
orbs:
  heroku: circleci/heroku@1.2.3
  node: circleci/node@4.1.0
workflows:
  heroku_deploy:
    jobs:
      - build:
        branches:
          only: master
        steps:
          - checkout
          - run: 
              name: "Installing"
              command: npm install
          - run:
              name: "Test"
              command: npm run test

      - heroku/deploy-via-git:
          requires:
            - build
          